WIKILINK_TEST_FIXTURES = {
    "basic": {
        "wikitext": "[[target_title]]",
        "plaintext": "target_title",
        "wikilinks": [("target_title", "target_title", 0, 12)],
        "categories": [],
    },
    "rename": {
        "wikitext": "[[target_title|anchor_text]]",
        "plaintext": "anchor_text",
        "wikilinks": [("target_title", "anchor_text", 0, 11)],
        "categories": [],
    },
    "kingdom": {
        "wikitext": "[[kingdom (biology)]]",
        "plaintext": "kingdom (biology)",
        "wikilinks": [("kingdom (biology)", "kingdom (biology)", 0, 17)],
        "categories": [],
    },
    "seattle": {
        "wikitext": "[[Seattle, Washington]]",
        "plaintext": "Seattle, Washington",
        "wikilinks": [("Seattle, Washington", "Seattle, Washington", 0, 19)],
        "categories": [],
    },
    "village": {
        "wikitext": "[[Wikipedia:Village pump]]",
        "plaintext": "Village pump",
        "wikilinks": [],
        "categories": [],
    },
    "style": {
        "wikitext": "[[Wikipedia:Manual of Style#Links]]",
        "plaintext": "Manual of Style",
        "wikilinks": [],
        "categories": [],
    },
    "style2": {
        "wikitext": "[[Wikipedia:Manual of Style#Italics|Italics]]",
        "plaintext": "Italics",
        "wikilinks": [],
        "categories": [],
    },
    "kingdom|": {
        "wikitext": "[[kingdom (biology)|]]",
        "plaintext": "kingdom (biology)",
        "wikilinks": [("kingdom (biology)", "kingdom (biology)", 0, 17)],
        "categories": [],
    },
    "seattle|": {
        "wikitext": "[[Seattle, Washington|]]",
        "plaintext": "Seattle, Washington",
        "wikilinks": [("Seattle, Washington", "Seattle, Washington", 0, 19)],
        "categories": [],
    },
    "village|": {
        "wikitext": "[[Wikipedia:Village pump|]]",
        "plaintext": "Village pump",
        "wikilinks": [],
        "categories": [],
    },
    "style|": {
        "wikitext": "[[Wikipedia:Manual of Style#Links|]]",
        "plaintext": "Manual of Style",
        "wikilinks": [],
        "categories": [],
    },
    "#self": {
        "wikitext": "[[#Links and URLs]]",
        "plaintext": "Links and URLs",
        "wikilinks": [],
        "categories": [],
    },
    "#self|s": {
        "wikitext": "[[#Links and URLs|Links and URLs]]",
        "plaintext": "Links and URLs",
        "wikilinks": [],
        "categories": [],
    },
    "micro-": {
        "wikitext": "[[micro-]]second",
        "plaintext": "micro-second",
        "wikilinks": [('micro-', 'micro-', 0, 6)],
        "categories": [],
    },
    "micro-nowiki": {
        "wikitext": "[[micro-]]<nowiki />second",
        "plaintext": "micro-second",
        "wikilinks": [('micro-', 'micro-', 0, 6)],
        "categories": [],
    },
    "category": {
        "wikitext": "a [[Category:Vowel letters]]",
        "plaintext": "a ",
        "wikilinks": [],
        "categories": ["Vowel letters"],
    },
    ":category": {
        "wikitext": "a [[:Category:Vowel letters]]",
        "plaintext": "a Vowel letters",
        "wikilinks": [],
        "categories": [],
    },
    ":category|": {
        "wikitext": "a [[:Category:Vowel letters|]]",
        "plaintext": "a Vowel letters",
        "wikilinks": [],
        "categories": [],
    },
    "nested_file": {
        "wikitext": "a [[File:Albedo-e hg.svg|thumb|upright=1.3|The percentage of [[diffuse reflection|diffusely reflected]] [[sunlight]] relative to various surface conditions]]", # noqa
        "plaintext": "a ",
        "wikilinks": [],
        "categories": [],
    },
}
